name: CI - Build & Push Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/api-gateway:latest
      - name: Build & push user-service
        uses: docker/build-push-action@v6
        with:
          context: ./user-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/user-service:latest
      - name: Build & push task-service
        uses: docker/build-push-action@v6
        with:
          context: ./task-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/task-service:latest
      - name: Build & push notification-service
        uses: docker/build-push-action@v6
        with:
          context: ./notification-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/notification-service:latest
